Feature/unique pinned posts
alleyinteractive/wp-curate pull request #202
Opened 2024-07-15 20:26 UTC by efuller

Ticket #48

2024-07-19 19:59 UTC, kevinfodness requested changes

2024-07-19 19:59 UTC, kevinfodness commented on composer.json
> +    "phpcs": "phpcs . -sn",
We shouldn't define these flags here. The `s` flag is already defined in `.phpcs.xml` and we don't want to suppress warnings.

2024-07-19 19:59 UTC, kevinfodness commented on entries/slotfills/deduplication/deduplication.tsx
> +import { useEffect } from '@wordpress/element';
We should import from React instead. The WP project has transitioned away from using `@wordpress/element` to using React directly.

2024-07-19 19:59 UTC, kevinfodness commented on services/deduplicate/index.ts
> +      posts?.forEach((post) => {
We can collapse this quite a bit:
```suggestion
    queryBlocks.forEach((queryBlock) => {
      queryBlock?.attributes?.posts?.forEach((post) => {
```

2024-07-19 19:59 UTC, kevinfodness commented on src/class-supported-post-types.php
> +				'type' => 'boolean',
We should set a default of `false`

2024-07-19 19:59 UTC, kevinfodness commented on src/post-ids/class-pinned-in-post-content.php
> +				if ( true === (bool) $post_level_unique_enabled ) {
No need to do several casts to boolean here, the `&&` will do it:
```suggestion
				if ( $post_level_unique && $post_level_deduplication ) {
```

2024-07-19 19:59 UTC, kevinfodness commented on tests/feature/UniquePinnedPostTest.php
> +				'post_title' => 'TheWrapTestPost 1',
We shouldn't have client names in tests in open source repos. Let's just make this "Test Post 1" etc for others in this file.

2024-07-23 13:40 UTC, efuller commented
@kevinfodness I've adjusted code per your review and requested another review. Could you have a look when you have a moment?

2024-07-23 20:27 UTC, kevinfodness approved these changes
🍣

2024-07-23 20:51 UTC, merged